MER: Add libsystrace support.
[MER]: This patch is not upstreamed as libsystrace is not widely in use, the
impact of additional function calls into QtBase was undesired, and the general
approach is not really generic to other types of tracing at this time.

libsystrace is a very small initialized-on-load wrapper for Android systrace
functionality, used so that data is written in order, regardless of how many
different libraries are writing data to it at a given time.

systrace is very useful for tracking system behavior, and for performance
analysis and improvement.

See also:
https://developer.android.com/tools/debugging/systrace.html

Some example uses of QSystraceEvent are also included in this patch. More are
undoubtedly possible. Additional tracing (e.g. counting the number of ongoing
HTTP requests and various other bits and pieces) are also easily accomplished.

Change-Id: I70012f6ddaa084f5b08685ee40795d7fafcd9c96

Conflicts:
	configure
	src/corelib/global/global.pri
	src/dbus/qdbusintegrator.cpp

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -616,6 +616,7 @@ CFG_MTDEV=auto
 CFG_JOURNALD=no
 CFG_SYSLOG=no
 CFG_SQLITE=qt
+CFG_LIBSYSTRACE=auto
 CFG_GIF=auto
 CFG_PNG=yes
 CFG_LIBPNG=auto
@@ -1697,6 +1698,13 @@ while [ "$#" -gt 0 ]; do
     sqlite)
         if [ "$VAL" = "system" ]; then
             CFG_SQLITE=system
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
+    libsystrace)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            CFG_LIBSYSTRACE="$VAL"
         else
             UNKNOWN_OPT=yes
         fi
@@ -4672,6 +4680,25 @@ if [ "$CFG_SYSLOG" != "no" ]; then
     fi
 fi
 
+if [ "$CFG_LIBSYSTRACE" != "no" ]; then
+    if compileTest unix/libsystrace "libsystrace"; then
+        CFG_LIBSYSTRACE=yes
+        QMAKE_CONFIG="$QMAKE_CONFIG libsystrace"
+        QMakeVar add DEFINES QT_USE_LIBSYSTRACE
+    else
+        if [ "$CFG_LIBSYSTRACE" != "auto" ] && [ "$CFG_CONFIGURE_EXIT_ON_ERROR" = "yes" ]; then
+            echo "libsystrace support cannot be enabled due to functionality tests!"
+            echo " Turn on verbose messaging (-v) to $0 to see the final report."
+            echo " If you believe this message is in error you may use the continue"
+            echo " switch (-continue) to $0 to continue."
+            exit 101
+        else
+            CFG_LIBSYSTRACE=no
+        fi
+    fi
+fi
+
+
 if [ "$CFG_LARGEFILE" = "auto" ]; then
     #Large files should be enabled for all Linux systems
     CFG_LARGEFILE=yes
@@ -7285,6 +7312,7 @@ report_support "  libinput................" "$CFG_LIBINPUT"
 report_support "  Logging backends:"
 report_support "    journald ..............." "$CFG_JOURNALD"
 report_support "    syslog   ..............." "$CFG_SYSLOG"
+report_support "  libsystrace ............" "$CFG_LIBSYSTRACE"
 report_support "  mtdev .................." "$CFG_MTDEV" yes "system library"
 report_support "  Networking:"
 [ "$XPLATFORM_MAC" = "yes" ] && \
